apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  labels:
    app: wcs-keycloak-cone-connector
  name: wcs-keycloak-cone-connector
  namespace: wcs-keycloak-cone-connector