apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  labels:
    app: wcs-keycloak-cone-connector
  name: wcs-keycloak-cone-connector
  namespace: wcs-keycloak-cone-connector
spec:
  provider: gcp
  secretObjects:
  - secretName: wcs-keycloak-cone-connector
    type: Opaque
    data:
    - objectName: wcs-keycloak-cone-connector-api-url
      key: KEYCLOAK_API_URL
    - objectName: wcs-keycloak-cone-connector-baton-client-id
      key: BATON_CLIENT_ID
    - objectName: wcs-keycloak-cone-connector-baton-client-secret
      key: BATON_CLIENT_SECRET
    - objectName: wcs-keycloak-cone-connector-keycloak-client-id
      key: KEYCLOAK_CLIENT_ID
    - objectName: wcs-keycloak-cone-connector-keycloak-client-secret
      key: KEYCLOAK_CLIENT_SECRET
    - objectName: wcs-keycloak-cone-connector-realm
      key: KEYCLOAK_REALM
    - objectName: wcs-keycloak-cone-connector-client-secret
      key: CLIENT_SECRET
    - objectName: wcs-keycloak-cone-connector-client-id
      key: CLIENT_ID
    - objectName: wcs-keycloak-cone-connector-display-name
      key: KEYCLOAK_DISPLAY_NAME
  parameters:
    secrets: |
      - resourceName: "projects/semi-wcs-admin/secrets/wcs-keycloak-cone-connector-api-url/versions/latest"
        fileName: "wcs-keycloak-cone-connector-api-url"
      - resourceName: "projects/semi-wcs-admin/secrets/wcs-keycloak-cone-connector-baton-client-id/versions/latest"
        fileName: "wcs-keycloak-cone-connector-baton-client-id"
      - resourceName: "projects/semi-wcs-admin/secrets/wcs-keycloak-cone-connector-baton-client-secret/versions/latest"
        fileName: "wcs-keycloak-cone-connector-baton-client-secret"
      - resourceName: "projects/semi-wcs-admin/secrets/wcs-keycloak-cone-connector-keycloak-client-id/versions/latest"
        fileName: "wcs-keycloak-cone-connector-keycloak-client-id"
      - resourceName: "projects/semi-wcs-admin/secrets/wcs-keycloak-cone-connector-keycloak-client-secret/versions/latest"
        fileName: "wcs-keycloak-cone-connector-keycloak-client-secret"
      - resourceName: "projects/semi-wcs-admin/secrets/wcs-keycloak-cone-connector-realm/versions/latest"
        fileName: "wcs-keycloak-cone-connector-realm"
      - resourceName: "projects/semi-wcs-admin/secrets/wcs-keycloak-cone-connector-client-secret/versions/latest"
        fileName: "wcs-keycloak-cone-connector-client-secret"
      - resourceName: "projects/semi-wcs-admin/secrets/wcs-keycloak-cone-connector-client-id/versions/latest"
        fileName: "wcs-keycloak-cone-connector-client-id"
      - resourceName: "projects/semi-wcs-admin/secrets/wcs-keycloak-cone-connector-display-name/versions/latest"
        fileName: "wcs-keycloak-cone-connector-display-name"